name: Trzsz Python2 Unit Test
on: [push]
jobs:
  unit-test-on-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7"]
    steps:
      - name: Checkout trzsz
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd trzsz-libs && python setup.py install && cd -
      - name: Run unit test for trzsz-libs
        run: python -m unittest discover trzsz-libs
      - name: Run unit test for trzsz-svr
        run: python -m unittest discover trzsz-svr
  unit-test-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["2.7"]
    steps:
      - name: Checkout trzsz
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd trzsz-libs && python setup.py install && cd -
      - name: Run unit test for trzsz-libs
        run: python -m unittest discover trzsz-libs
      - name: Run unit test for trzsz-svr
        run: python -m unittest discover trzsz-svr
  unit-test-on-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["2.7"]
    steps:
      - name: Checkout trzsz
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd trzsz-libs && python setup.py install && cd -
      - name: Run unit test for trzsz-libs
        run: python -m unittest discover trzsz-libs
      - name: Run unit test for trzsz-svr
        run: python -m unittest discover trzsz-svr
